apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5uin
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-5uin@sha256:79a470bac17caf4ebdd12f75a5b413f69fd7e4874498fe7ef62010471e1ddb4e
        name: my-nodejs
        resources: {}
status: {}
